---
name: "Prerelease"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    name: "Prerelease"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3.2.0"

      - name: "Build"
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm i
      - run: npm run build
      - run: npm test

      - name: "Update latest release"
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          files: "builds/*.zip"
