---
name: "Tagged release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3.2.0"

      - name: "Build"
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm i
      - run: npm run build
      - run: npm test

      - name: "Create new release"
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "extension/*.zip"
